### ISSUE TITLE
rosbags are missing

### ISSUE THREAD

**Issue by brolinA** [leggedrobotics/wild_visual_navigation#307]
Hi,
I wanted to understand how the project works with the simulation. So while running the following command it throws an error since the `path_to_mission` directory is missing in the repository. Could you please mention if the file is actually missing or we are expected to record our own bag files.

`rosbag play --clock path_to_mission/*.bag`

**Note:**
There is also a spelling mistake in the original README file. It says `robag` instead of `rosbag`.

**Comment by xuyuxiu83** [comment]
Now I have the same question. So where is the rosbag and why this issue has been closed?
