### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Yinmlmaoliang** [leggedrobotics/wild_visual_navigation#309]
When I start the Gazebo simulation environment and the RViz window as the main interface.
[Msg] Waiting for master.
[Msg] Connected to gazebo master 
[Msg] Publicized address: 
[Msg] Loading world file [/root/catkin_ws/src/wild_visual_navigation/wild_visual_navigation_jackal/worlds/outdoor.world]
[ INFO] [1720660848.245358585]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1720660848.364386093]: Physics dynamic reconfigure ready.
[ERROR] [1720660848.613223, 0.001000]: bad callback: <function gazebo_callback at 0x7fe93ed40e50>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/root/catkin_ws/src/wild_visual_navigation/wild_visual_navigation_jackal/scripts/carrot_follower.py", line 55, in gazebo_callback
    robot_x, robot_y, robot_yaw = msg_to_se2(msg.pose[1])
IndexError: list index out of range

[ERROR] [1720660848.613761, 0.001000]: bad callback: <function gazebo_callback at 0x7f8cfd6b91f0>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/root/catkin_ws/src/wild_visual_navigation/wild_visual_navigation_jackal/scripts/gazebo_world_publisher.py", line 65, in gazebo_callback
    T_world_base = msg_to_se3(msg.pose[1])  # this is the base_link pose in world frame (from gazebo)
IndexError: list index out of range

**Comment by nankaixiaokai** [comment]
How did you solve it？

**Comment by mmattamala** [comment]
It's very likely that something didn't launch correctly - because the carrot follower is subscribing an apparently ill-defined message.

**Comment by fwx20020105** [comment]
> When I start the Gazebo simulation environment and the RViz window as the main interface.当我启动凉亭模拟环境，将 RViz 窗口作为主界面时， [Msg] Waiting for master.[新闻]等师父。 [Msg] Connected to gazebo master[新闻]连接凉亭主人 [Msg] Publicized address:[新闻]公开演讲： [Msg] Loading world file [/root/catkin_ws/src/wild_visual_navigation/wild_visual_navigation_jackal/worlds/outdoor.world][新闻]加载世界文件 [/root/catkin_ws/src/wild_visual_navigation/wild_visual_navigation_jackal/worlds/outdoor.world] [ INFO] [1720660848.245358585]: waitForService: Service [/gazebo/set_physics_properties] is now available.[信息][1720660848.245358585]： waitForService：服务 [/gazebo/set_physics_properties] 现已开放。 [ INFO] [1720660848.364386093]: Physics dynamic reconfigure ready.[信息][1720660848.364386093]：物理动态重构准备就绪。 [ERROR] [1720660848.613223, 0.001000]: bad callback: <function gazebo_callback at 0x7fe93ed40e50>[错误][1720660848.613223， 0.001000]：错误回调：在 0x7fe93ed40e50>gazebo_callback 函数< Traceback (most recent call last):追溯（最近一次通话）： File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback文件“/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py”，第 750 行，在_invoke_callback cb(msg)  CB（MSG） File "/root/catkin_ws/src/wild_visual_navigation/wild_visual_navigation_jackal/scripts/carrot_follower.py", line 55, in gazebo_callback文件“/root/catkin_ws/src/wild_visual_navigation/wild_visual_navigation_jackal/scripts/carrot_follower.py”，第 55 行，gazebo_callback robot_x, robot_y, robot_yaw = msg_to_se2(msg.pose[1])robot_x， robot_y， robot_yaw = msg_to_se2（主信。pose[1]） IndexError: list index out of rangeIndexError：列表索引超出范围
> 
> [ERROR] [1720660848.613761, 0.001000]: bad callback: <function gazebo_callback at 0x7f8cfd6b91f0>[错误][1720660848.613761， 0.001000]：错误回调：<函数gazebo_callback在0x7f8cfd6b91f0> Traceback (most recent call last):追溯（最近一次通话）： File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback文件“/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py”，第 750 行，在_invoke_callback cb(msg)  CB（MSG） File "/root/catkin_ws/src/wild_visual_navigation/wild_visual_navigation_jackal/scripts/gazebo_world_publisher.py", line 65, in gazebo_callback文件“/root/catkin_ws/src/wild_visual_navigation/wild_visual_navigation_jackal/scripts/gazebo_world_publisher.py”，第 65 行，在 gazebo_callback T_world_base = msg_to_se3(msg.pose[1]) # this is the base_link pose in world frame (from gazebo)T_world_base = msg_to_se3（主信。pose[1]） # 这是世界系中的 base_link 姿（来自凉亭） IndexError: list index out of rangeIndexError：列表索引超出范围

I'm sorry to bother you.I found that the Google Drive links for checkpoints and rosbags are returning 404 errors. I was wondering if you still have the relevant field rosbag files available. If so, could you please send them to my email address: 1035664828@qq.com? I would be extremely grateful.
